Importing necessary libraries

In [1]:
import numpy as np

Creating arrays

In [3]:
lst_1=[1,2,3,4]

In [5]:
arr_1=np.array(lst_1)

In [6]:
arr_1

array([1, 2, 3, 4])

In [21]:
lst2=[[1,2],[3,4]]

In [22]:
arr2=np.array(lst2)

In [23]:
arr2

array([[1, 2],
       [3, 4]])

Modifing the array data

In [11]:
arr_1[2]=7

In [12]:
arr_1

array([1, 2, 7, 4])

In [24]:
arr2[1][0]=7

In [25]:
arr2

array([[1, 2],
       [7, 4]])

Arithmetic operators

In [26]:
arr_1

array([1, 2, 7, 4])

In [27]:
arr2

array([[1, 2],
       [7, 4]])

In [28]:
arr_1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [30]:
lst3=[5,6,7,8]


In [32]:
arr3=np.array(lst3)

In [33]:
arr3

array([5, 6, 7, 8])

In [34]:
arr_1+arr3

array([ 6,  8, 14, 12])

In [35]:
arr2+7

array([[ 8,  9],
       [14, 11]])

In [36]:
arr_1+7

array([ 8,  9, 14, 11])

In [37]:
arr_1-7

array([-6, -5,  0, -3])

activity 1
create an array

In [42]:
lst4=[5,10,15,20]

In [43]:
arr4=np.array (lst4)

In [44]:
arr4

array([ 5, 10, 15, 20])

Activity 2


In [48]:
lst5=[10,20,30,40]

In [49]:
arr=np.array(lst5)

In [50]:
arr

array([10, 20, 30, 40])

In [51]:
arr[3]

np.int64(40)

Activity 3
change an element

In [53]:
arr[0]=100

In [54]:
arr

array([100,  20,  30,  40])

Activity 4
add the two arrays andprint the result

In [55]:
lst=[1,2,3]


In [57]:
lst1=[4,5,6]

In [58]:
arr0=np.array(lst)

In [59]:
arr67=np.array (lst1)

In [60]:
arr0+arr67

array([5, 7, 9])

activity 5
multiply to arrays

In [61]:
lst8=[2,3,4]

In [62]:
arr6=np.array(lst8)

In [63]:
lst9=[5,6,7]

In [64]:
arr7=np.array(lst9)

In [65]:
arr7*arr6

array([10, 18, 28])

Activity 6
Square the nbumbers

In [71]:
lst8=[1,2,3,4]

In [72]:
arr9=np.array(lst8)

In [73]:
arr9*arr9

array([ 1,  4,  9, 16])

Activity 7                                                            
add 10 to every number


In [76]:
lst_9=[5,10,15]

In [77]:
arr_=np.array(lst_9)

In [78]:
arr_+10

array([15, 20, 25])

Activity 8
multiply every element by3

In [79]:
lst_=[2,4,6]

In [80]:
arr__=np.array (lst_)

In [81]:
arr__*3

array([ 6, 12, 18])

Activity 9
ptint the following 2D array

In [85]:
lst6 =[[1,2,3],[4,5,6]]

In [88]:
arr8=np.array(lst6)

In [89]:
arr8

array([[1, 2, 3],
       [4, 5, 6]])

Activity 9
print the element in the row 2 and colum 3

In [90]:
lst_2=[[10,20,30],[40,50,60]]

In [91]:
arr_2=np.array(lst_2)

In [92]:
arr_2[1][2]

np.int64(60)

In [93]:
arr_1

array([1, 2, 7, 4])

In [94]:
np.sum(arr_1)

np.int64(14)

In [95]:
np.mean(arr_1)

np.float64(3.5)

In [99]:
np.max(arr_1)

np.int64(7)

In [100]:
np.min (arr_1)

np.int64(1)

Matric multiplication

In [101]:
m1=np.array([[1,2],[3,4]])

In [102]:
m1

array([[1, 2],
       [3, 4]])

In [105]:
m2=np.array([[5,6],[7,8]])

In [106]:
m2

array([[5, 6],
       [7, 8]])

In [107]:
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])