Installing Numpy library

In [ ]:
!pip install numpy

Importing numpy library

In [ ]:
import numpy as np

numpy creation

In [ ]:
lst_1=[1,2,3,4]

In [ ]:
lst_1

[1, 2, 3, 4]

In [ ]:
arr1=np.array(lst_1)

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
lst_2=[[1,2],[3,4]]

In [89]:
lst_2

[[1, 2], [3, 4]]

In [90]:
arr_2=np.array(lst_2)

In [91]:
arr_2

array([[1, 2],
       [3, 4]])

Activity 1
(i)[2,3,4,5]

In [ ]:
lst_3=[2,3,4,5]

In [ ]:
lst_3

[2, 3, 4, 5]

In [ ]:
arr_3=np.array(lst_3)

In [ ]:
arr_3

array([2, 3, 4, 5])

Activity 2

```
(ii)[[1,2,3,4],[7,8,9]]
```



In [ ]:
lst_4=[[1,2,4],[7,8,9]]

In [ ]:
lst_4

[[1, 2, 4], [7, 8, 9]]

In [ ]:
arr_4=np.array(lst_4)

In [ ]:
arr_4

array([[1, 2, 4],
       [7, 8, 9]])

Activity 3                                                   
```
(iii) [0,1,7]
```



In [ ]:
lst_5=[0,1,7]

In [ ]:
lst_5

[0, 1, 7]

In [ ]:
arr_5=np.array(lst_5)

In [ ]:
arr_5

array([0, 1, 7])

Activity 4

```
(iv) [[1,3,5],[8,9,10],[11,12,13],[99,100,101]]
```



In [ ]:
lst_6=[[1,3,5],[8,9,10],[11,12,13],[99,100,101]]

In [ ]:
lst_6

[[1, 3, 5], [8, 9, 10], [11, 12, 13], [99, 100, 101]]

In [ ]:
arr_6=np.array(lst_6)

In [ ]:
arr_6

array([[  1,   3,   5],
       [  8,   9,  10],
       [ 11,  12,  13],
       [ 99, 100, 101]])

Special arrays

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [57]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Activity 5

In [71]:
np.zeros((7,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Activity 6

In [72]:
np.ones((10,11))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Activity 7

In [76]:
np.eye((12))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [75]:
np.arange(3,60,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57])

In [78]:
arr1

array([1, 2, 3, 4])

In [79]:
arr1.shape

(4,)

In [81]:
arr1.ndim

1

In [82]:
arr1.dtype

dtype('int64')

In [92]:
arr_2

array([[1, 2],
       [3, 4]])

In [93]:
arr_2.shape

(2, 2)

In [94]:
arr_2.ndim

2

In [95]:
arr_2.dtype

dtype('int64')

Indeking and slicing

In [96]:
arr1

array([1, 2, 3, 4])

In [97]:
arr1[2]

np.int64(3)

In [98]:
arr1[1:3]

array([2, 3])

In [99]:
arr_2

array([[1, 2],
       [3, 4]])

In [103]:
arr_2[1]

array([3, 4])

In [104]:
arr_2[1][0]

np.int64(3)

In [105]:
arr_2[1][1]

np.int64(4)

In [106]:
lst=[[3,6,9],[12,15,18],[21,24,27]]

In [107]:
arr2=np.array(lst)

In [108]:
arr2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [110]:
arr2[1][1:3]

array([15, 18])

Activity 8

In [112]:
lst0=[[11,22,33,44],[55,66,77,88],[99,111,222,33]]

In [113]:
arr0=np.array(lst0)

In [114]:
arr0

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 111, 222,  33]])

In [115]:
arr0[2][1:4]

array([111, 222,  33])

Activity 9

In [116]:
lst_7=[[71,72,73,74],[75,76,77,78],[79,80,81,82],[83,84,85,86]]

In [117]:
arr7=np.array(lst_7)

In [118]:
arr7

array([[71, 72, 73, 74],
       [75, 76, 77, 78],
       [79, 80, 81, 82],
       [83, 84, 85, 86]])

In [129]:
arr7[2:4][ : ,1:3]

array([[80, 81],
       [84, 85]])

In [131]:
arr7[1:3,1:3]

array([[76, 77],
       [80, 81]])

In [132]:
arr7[0:3,0:3]

array([[71, 72, 73],
       [75, 76, 77],
       [79, 80, 81]])

In [133]:
arr7[0:3,1:3]

array([[72, 73],
       [76, 77],
       [80, 81]])

In [134]:
arr7[1:4,2:3]

array([[77],
       [81],
       [85]])